#MySql ????
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/articles
    username: ${DB_USER}
    password: ${DB_PW}
  sql:
    init:
      mode: always
  #always : 매번, embedded : 내장 DB만, never : 모든 동작 안함
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show-sql: true
        format-sql: true
